### ISSUE TITLE
[Languages] Language switcher does not dissappear after deactivation of language in Settings

### ISSUE THREAD

**Issue by overeha** [code4romania/website-factory#13]
I have deactivated a newly created language in the dashboard. However it did not remove it from the options in pages of blog post or anywhere else. While the Activation says False, I can still switch in between the languages.

![image](https://user-images.githubusercontent.com/45068169/169546090-90172e49-8db4-4a26-8da2-05d9ec3c4f85.png)

**Comment by andreiio** [comment]
This needs a better visual indicator of which languages are active and which are not.
