### ISSUE TITLE
[Languages] 502 bad Gateway on language edit

### ISSUE THREAD

**Issue by overeha** [code4romania/website-factory#18]
I get this when I want to edit a language. It was Hungarian and I tried to edit it to ru/Russian and I got this error. 
I do not get any error when I check the **_Activated_** checkbox and I save, only when I edit the main fields: **_Cod, Nume_**. 

However, even with this error, changes are saved. I now have Russian instead of Hungarian available in pages.

**Comment by andreiio** [comment]
Investigating
