### ISSUE TITLE
[Bug]   Class "Faker\Factory" not found on  runing php artisan db:seed

### ISSUE THREAD

**Issue by gheorghelupu17** [code4romania/website-factory#256]
WF version: edge;
WF instance: internal

<img width="292" alt="Screenshot 2023-02-20 at 15 10 38" src="https://user-images.githubusercontent.com/46172059/220117992-b3b21685-e045-4925-a9b7-410b5dbcb7c8.png">

**Comment by andreiio** [comment]
`artisan db:seed` e doar pentru dev environment
