### ISSUE TITLE
Issue when starting the project 

### ISSUE THREAD

**Issue by tudoramariei** [code4romania/website-factory#658]
**Describe the bug**

There is an error in the project documentation. [The last step in the init instructions](https://github.com/code4romania/website-factory?tab=readme-ov-file#development) throws the following error:
```
 ./vendor/bin/sail npm run watch
npm ERR! Missing script: "watch"
npm ERR!
npm ERR! To see a list of scripts, run:
npm ERR!   npm run
npm ERR! A complete log of this run can be found in: /home/sail/.npm/_logs/2024-02-24T11_49_46_094Z-debug-0.log
```

**Comment by themujahidkhan** [comment]
Hi @tudoramariei 

I can see that there is no `watch` script associated with it, which is why you are getting that error.

Screenshot of **Package.json** file
![image](https://github.com/code4romania/website-factory/assets/72564155/758a8b5d-7546-4ede-a5c0-7efcbef040ef)
