### ISSUE TITLE
[Site settings] Color option for body text in Global Notice

### ISSUE THREAD

**Issue by overeha** [code4romania/website-factory#7]
It would a nice to have if we could also pick the text color for the body text in the Global Notice banner. 
Because currently with darker colors the contrast is very low. Black on dark blue for example etc....

![image](https://user-images.githubusercontent.com/45068169/169535102-17727f4f-a1ec-462c-86e5-f706a3515776.png)

**Comment by andreiio** [comment]
Done in #57
